services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio
    ports:
      - "3035:3000"
    networks:
      - app-net
    restart: unless-stopped

networks:
  app-net:
    driver: bridge
    name: app-net
